### ISSUE TITLE
Priorities (Assign To New Task)

### ISSUE THREAD

**Issue by JamesMowery** [JamesMowery/todoistify#1]
# Priorities (Assign To New Task)

Attach a priority to a task.
## Tasks
- [ ] ~~Implement a syntax to identify the priority (e.g., "!p1," "!p2," etc., or "p1," "p2," etc).~~ (Not Needed)
- [ ] ~~Extract the priority from the query.~~ (Not Needed)
- [ ] ~~Use logic to apply the correct priority code to the API call.~~ (Not Needed)
- [x] Update docs with explanation of new behavior.
