### ISSUE TITLE
Labels (Assign Existing Label To New Task)

### ISSUE THREAD

**Issue by JamesMowery** [JamesMowery/todoistify#2]
# Labels (Assign Existing Label To New Task)

Add the ability to assign an existing label to a task.
## Tasks
- [ ] ~~Detect & extract labels when typed (using the syntax "@label_name")~~ (Not needed)
- [ ] ~~Attach the label to the task, and submit it with the Todoist API call~~ (Not needed)
- [ ] Update documentation to reflect the added functionality
