### ISSUE TITLE
Due Date (Assign Due Date To New Task)

### ISSUE THREAD

**Issue by JamesMowery** [JamesMowery/todoistify#3]
# Due Date (Assign Due Date To New Task)

Add the ability to assign a due date to a new task.
## Tasks
- [ ] Come up with a Workflow syntax to associate a Todoist due date (using Todoist's string syntax)
- [ ] Detect & extract due date when entered 
- [ ] Attach the due date to the task, and submit it with the Todoist API call
- [ ] Update documentation to reflect the added functionality

**Comment by xilopaint** [comment]
Any news about this?
